# .github/workflows/update-readme.yml
name: Update LICENSE

on:
  schedule:
    - cron: '0 0 1 1 *' # Runs every year on January 1st at 12 AM
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  update-license:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Run update script
        run: |
          cd .github/workflows
          node update-license.js
          cd ../../
          
      - name: Check for changes
        id: check-changes
        run: |
          git add LICENSE
          git diff --cached --exit-code || echo "changes detected" > has_changes.txt

      - name: Set output
        id: set-output
        run: echo "::set-output name=has_changes::$(if [ -f has_changes.txt ]; then echo true; else echo false; fi)"
        shell: bash

      - name: Commit changes
        if: steps.set-output.outputs.has_changes == 'true'
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git commit -m 'Update LICENSE with current year'
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
